Find factorial
js-tasks-ru/jsbasic-20210809_denis-kuznetsov5 pull request #2
Opened 2021-08-15 00:20 UTC by DenisPr-SPb

2021-08-15 00:21 UTC, jsru commented
Добавляю преподавателя (@koalex) для код-ревью.

2021-08-15 15:55 UTC, jsru commented
Проверьте, пожалуйста, ваше решение, не все тесты прошли (PR не будет принят до тех пор, пока **все** добавленные задачи не будут решены).

2021-08-15 19:25 UTC, jsru commented
Проверьте, пожалуйста, ваше решение, не все тесты прошли (PR не будет принят до тех пор, пока **все** добавленные задачи не будут решены).

2021-08-16 03:56 UTC, jsru commented
Проверьте, пожалуйста, ваше решение, не все тесты прошли (PR не будет принят до тех пор, пока **все** добавленные задачи не будут решены).

2021-08-16 04:01 UTC, koalex requested changes
Нужно вернуть как было `ChromeHeadless` иначе тесты на **GitHub** не пройдут. Для локального тестирования можешь менять на `Firefox`, но перед отправкой **PR** менять на `ChromeHeadless`

2021-08-16 04:01 UTC, koalex commented on karma.conf.js
> +    browsers: ['Firefox'],
Нужно вернуть как было `ChromeHeadless` иначе тесты на GitHub не пройдут. Для локального тестирования можешь менять на Firefox, но перед отправкой PR менять на `ChromeHeadless`

2021-08-16 05:57 UTC, jsru commented
Добавляю преподавателя (@koalex) для код-ревью.

2021-08-16 05:57 UTC, DenisPr-SPb commented on karma.conf.js
> +    browsers: ['Firefox'],
Исправил.

2021-08-16 08:45 UTC, koalex approved these changes

2021-08-16 08:45 UTC, merged